// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-6G8njYK9I8WXh9bIpkknsaYhLsoQxmQ',
    appId: '1:457458718791:web:23250d69999315026e3962',
    messagingSenderId: '457458718791',
    projectId: 'nadhilah-fb',
    authDomain: 'nadhilah-fb.firebaseapp.com',
    storageBucket: 'nadhilah-fb.appspot.com',
    measurementId: 'G-XFYYSN3RGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANwFvANSyUol3wdi-ueB5xgQjOBG5h0zk',
    appId: '1:457458718791:android:89e060c069c9eaed6e3962',
    messagingSenderId: '457458718791',
    projectId: 'nadhilah-fb',
    storageBucket: 'nadhilah-fb.appspot.com',
  );
}
